services:
  - type: web
    name: etronics-fastapi-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn bot:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "вставь_сюда_токен_бота"
      - key: VK_GROUP_TOKEN
        value: "вставь_сюда_vk_токен"
      - key: WEBHOOK_URL
        value: "https://etronics-fastapi-bot.onrender.com"